name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opentelemetry-sdk
          pip install opentelemetry-exporter-otlp
          echo "Dependencies installed"

      - name: Run tests with OpenTelemetry
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: "http://3.147.48.200:4317"
          OTEL_SERVICE_NAME: "github-actions-pipeline"
        run: |
          python -m opentelemetry.instrumentation.auto_instrument
          echo "Running tests with OpenTelemetry instrumentation"
          # Replace the following line with your actual test command
          echo "test ran"

      - name: Push Job Metrics to Pushgateway
        run: |
          echo "Pushing metrics to Pushgateway"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
