name: CI Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install OpenTelemetry
        run: |
          npm install @opentelemetry/api @opentelemetry/sdk-node @opentelemetry/exporter-otlp-grpc

      - name: Instrument with OpenTelemetry
        run: |
          node -e "const { NodeTracerProvider } = require('@opentelemetry/sdk-trace-node');
          const { SimpleSpanProcessor } = require('@opentelemetry/sdk-trace-base');
          const { OTLPTraceExporter } = require('@opentelemetry/exporter-otlp-grpc');
          const provider = new NodeTracerProvider();
          const exporter = new OTLPTraceExporter({ url: 'http://your-ec2-ip:4317' });
          provider.addSpanProcessor(new SimpleSpanProcessor(exporter));
          provider.register();"

      - name: Run tests
        run: echo "done"
