name: CI/CD with Build Status to Pushgateway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate a build
        id: build-step
        run: |
          start_time=$(date +%s)
          echo "Simulating a build..."
          sleep 2  # Simulate some work
          echo "hi
          exit 0
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "BUILD_DURATION=$duration" >> $GITHUB_OUTPUT
          echo "Build duration calculated: $duration seconds"

      - name: Push build status to Pushgateway
        if: always()
        run: |
          STATUS="${{ job.status == 'success' && 'success' || 'failure' }}"
          DURATION="${{ steps.build-step.outputs.BUILD_DURATION }}"
          if [ -z "$DURATION" ]; then
            echo "Error: BUILD_DURATION is empty. Setting default value."
            DURATION=0
          fi
          cat <<EOF > metrics.txt
          build_status{repository="${{ github.repository }}",branch="${{ github.ref_name }}",run_id="${{ github.run_id }}",status="$STATUS"} 1
          build_duration_seconds{repository="${{ github.repository }}",branch="${{ github.ref_name }}",run_id="${{ github.run_id }}",status="$STATUS"} $DURATION
          EOF
          echo "Metrics being pushed to Pushgateway:"
          cat metrics.txt
          curl --data-binary @metrics.txt -v http://a855f71a64930465fb5339ea184d1d3f-381870272.us-east-1.elb.amazonaws.com:9091/metrics/job/build_pipeline || {
            echo "Failed to push metrics to Pushgateway. Exit code: $?"
            exit 1
          }
