name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Push Job Metrics to Pushgateway
        run: |
          echo "ci_build_duration_seconds{job='ci_pipeline'} $(date +%s)" | curl --data-binary @- http://3.147.48.200:9091/metrics/job/ci_pipeline
          echo "ci_build_status{job='ci_pipeline'} 1" | curl --data-binary @- http://3.147.48.200:9091/metrics/job/ci_pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN}}
