name: CI/CD with Build Status to Pushgateway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate a build
        id: build-step
        run: |
          echo "Running a fake build..."
          exit 0 # Replace with your actual build commands (e.g., npm install, npm run build)

      - name: Push build status to Pushgateway
        if: always() # Runs whether the build succeeds or fails
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          STATUS=$([[ ${{ job.status }} == "success" ]] && echo 1 || echo 0)
          echo "build_status{repository=\"${{ github.repository }}\",branch=\"${{ github.ref_name }}\"} $STATUS" | \
          curl --data-binary @- http://af14c7555b43943c897f47b84d25f423-1894518563.us-east-1.elb.amazonaws.com:9091/metrics/job/build_pipeline
